/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package E_Bank_Client;

import javax.swing.JOptionPane;

/**
 *
 * @author Raveen S Rathnayake
 */
public class AddCusView extends javax.swing.JFrame {

    /**
     * Creates new form AddEmpView
     */
    public AddCusView() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTxtMobile = new javax.swing.JTextField();
        jBtnAddCus = new javax.swing.JButton();
        jLblHeading = new javax.swing.JLabel();
        jLblName = new javax.swing.JLabel();
        jLblposition = new javax.swing.JLabel();
        jLblusername = new javax.swing.JLabel();
        jLblPwd = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jBtnLogOut = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jComboAccType = new javax.swing.JComboBox<>();
        jTxtEmail = new javax.swing.JTextField();
        jTxtSortCode = new javax.swing.JTextField();
        jTxtBalance = new javax.swing.JTextField();
        jTxtCard = new javax.swing.JTextField();
        jTxtCusName = new javax.swing.JTextField();
        jTxtBDay = new javax.swing.JTextField();
        jTxtAddress = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTxtAccNum = new javax.swing.JTextField();
        jLblMessage = new javax.swing.JLabel();
        jBtnMain = new javax.swing.JButton();
        jBtnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(400, 470));

        jBtnAddCus.setText("Add Customer");
        jBtnAddCus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAddCusActionPerformed(evt);
            }
        });

        jLblHeading.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLblHeading.setText("Customer Registration");

        jLblName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLblName.setText("Name");

        jLblposition.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLblposition.setText("Birthdate");

        jLblusername.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLblusername.setText("Address");

        jLblPwd.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLblPwd.setText("Mobile");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Balance");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Account Type");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Account Number");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Sort Code");

        jBtnLogOut.setText("Log Out");
        jBtnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnLogOutActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Card");

        jComboAccType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Personnel", "Joint", "Foreign Remittance", "Savings" }));
        jComboAccType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboAccTypeActionPerformed(evt);
            }
        });

        jTxtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtEmailActionPerformed(evt);
            }
        });

        jTxtBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtBalanceActionPerformed(evt);
            }
        });

        jTxtCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtCardActionPerformed(evt);
            }
        });

        jTxtCusName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtCusNameActionPerformed(evt);
            }
        });

        jTxtBDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtBDayActionPerformed(evt);
            }
        });

        jTxtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtAddressActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Email");

        jLblMessage.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jBtnMain.setText("Main Menu");
        jBtnMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnMainActionPerformed(evt);
            }
        });

        jBtnBack.setText("Back");
        jBtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jBtnBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtnMain)
                .addGap(50, 50, 50)
                .addComponent(jBtnLogOut)
                .addGap(51, 51, 51))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jLblHeading))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLblPwd)
                                        .addComponent(jLblusername)
                                        .addComponent(jLblposition)
                                        .addComponent(jLblName)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)))
                                .addGap(44, 44, 44)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTxtAccNum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jTxtMobile, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jTxtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jTxtBDay, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jTxtCusName, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jComboAccType, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jTxtEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jTxtSortCode, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTxtBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTxtCard, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLblMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(jBtnAddCus)))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLblHeading)
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblName)
                    .addComponent(jTxtCusName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblposition)
                    .addComponent(jTxtBDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblusername)
                    .addComponent(jTxtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblPwd)
                    .addComponent(jTxtMobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboAccType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTxtAccNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTxtSortCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTxtBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTxtCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jLblMessage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtnAddCus)
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnLogOut)
                    .addComponent(jBtnMain)
                    .addComponent(jBtnBack))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtAddressActionPerformed

    private void jTxtBDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtBDayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtBDayActionPerformed

    private void jTxtCusNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtCusNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtCusNameActionPerformed

    private void jBtnAddCusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAddCusActionPerformed

            if(checkFields()){
                try{
                    String name=jTxtCusName.getText();
                    String bday=jTxtBDay.getText();
                    String address=jTxtAddress.getText();
                    int mobile=Integer.valueOf(jTxtMobile.getText());
                    String accType=jComboAccType.getSelectedItem().toString();
                    String email=jTxtEmail.getText();
                    int accNum=Integer.valueOf(jTxtAccNum.getText());
                    String sortCode=jTxtSortCode.getText();
                    int balance=Integer.valueOf(jTxtBalance.getText());
                    String cardNum=jTxtCard.getText();
                    boolean flag=registerClient(name,bday,address,mobile,email,accNum,accType,sortCode,balance,cardNum);
                    if(!flag){
                        JOptionPane.showMessageDialog(this, "Error! Try again with correct data");
                        //jLblMessage.setText("Error! Try again with correct data");
                    }else{
                        JOptionPane.showMessageDialog(this, "Customer added successfully!");
                    }
                }catch(Exception e){
                    JOptionPane.showMessageDialog(this, "Mobile, Account Number, Balance fields are only allowed digits only");
                }
                       
            }else{
                JOptionPane.showMessageDialog(this, "Please fill all the fields with valid data!");
            }
        
    }//GEN-LAST:event_jBtnAddCusActionPerformed

    private void jComboAccTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboAccTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboAccTypeActionPerformed

    private void jTxtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtEmailActionPerformed

    private void jBtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBackActionPerformed
        CusRegistrationView cus=new CusRegistrationView();
        this.dispose();
        cus.setVisible(true);
    }//GEN-LAST:event_jBtnBackActionPerformed

    private void jBtnMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnMainActionPerformed
        MainMenuView main=new MainMenuView();
        this.dispose();
        main.setVisible(true);
    }//GEN-LAST:event_jBtnMainActionPerformed

    private void jBtnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLogOutActionPerformed
        EmpLoginView login=new EmpLoginView();
        this.dispose();
        login.setVisible(true);
    }//GEN-LAST:event_jBtnLogOutActionPerformed

    private void jTxtBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtBalanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtBalanceActionPerformed

    private void jTxtCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtCardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtCardActionPerformed
                                              
    /*
    *checks whether the fields are empty
    */
    private boolean checkFields(){
        boolean flag=true;
        if(jTxtCusName.getText().equals("")){
            flag= false;
        }
        else if(jTxtBDay.getText().equals("")){
            flag= false;
        }
        else if(jTxtAddress.getText().equals("")){
            flag= false;
        }
        else if(jTxtMobile.getText().equals("") && jTxtMobile.getText().length()<=10){
            flag= false;
        }
        else if(jTxtEmail.getText().equals("")){
            flag= false;
        }
        else if(jTxtAccNum.getText().equals("")){
            flag= false;
        }
        else if(jTxtSortCode.getText().equals("")){
            flag= false;
        }
        else if(jTxtCard.getText().equals("")){
            flag= false;
        }
        else if(jTxtBalance.getText().equals("")){
            flag= false;
        }
        else if(jComboAccType.getSelectedItem().equals("")){
            flag= false;
        }
        
        return flag;
    }
    
    /**
     * @param args the command line arguments
     
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddCusView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddCusView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddCusView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddCusView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddCusView().setVisible(true);
            }
        });
    } */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAddCus;
    private javax.swing.JButton jBtnBack;
    private javax.swing.JButton jBtnLogOut;
    private javax.swing.JButton jBtnMain;
    private javax.swing.JComboBox<String> jComboAccType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLblHeading;
    private javax.swing.JLabel jLblMessage;
    private javax.swing.JLabel jLblName;
    private javax.swing.JLabel jLblPwd;
    private javax.swing.JLabel jLblposition;
    private javax.swing.JLabel jLblusername;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTxtAccNum;
    private javax.swing.JTextField jTxtAddress;
    private javax.swing.JTextField jTxtBDay;
    private javax.swing.JTextField jTxtBalance;
    private javax.swing.JTextField jTxtCard;
    private javax.swing.JTextField jTxtCusName;
    private javax.swing.JTextField jTxtEmail;
    private javax.swing.JTextField jTxtMobile;
    private javax.swing.JTextField jTxtSortCode;
    // End of variables declaration//GEN-END:variables

    private static boolean registerClient(java.lang.String arg0, java.lang.String arg1, java.lang.String arg2, int arg3, java.lang.String arg4, int arg5, java.lang.String arg6, java.lang.String arg7, int arg8, java.lang.String arg9) {
        e_bank_ws.EBankClient_Service service = new e_bank_ws.EBankClient_Service();
        e_bank_ws.EBankClient port = service.getEBankClientPort();
        return port.registerClient(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
    }
}
