/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package E_Bank_Client;

/**
 *
 * @author Raveen S Rathnayake
 */
public class CusRegistrationView extends javax.swing.JFrame {

    /**
     * Creates new form EmpRegistrationView
     */
    public CusRegistrationView() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelEmpReg = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jBtnAddCus = new javax.swing.JButton();
        jBtnEditCus = new javax.swing.JButton();
        jBtnDeleteCus = new javax.swing.JButton();
        jBtnEmpRegLogOut = new javax.swing.JButton();
        jBtnEmpRegMain = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelEmpReg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Customer Management");

        jBtnAddCus.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jBtnAddCus.setText("Add a Customer");
        jBtnAddCus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAddCusActionPerformed(evt);
            }
        });

        jBtnEditCus.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jBtnEditCus.setText("Edit Details");
        jBtnEditCus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEditCusActionPerformed(evt);
            }
        });

        jBtnDeleteCus.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jBtnDeleteCus.setText("Delete a Customer");
        jBtnDeleteCus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDeleteCusActionPerformed(evt);
            }
        });

        jBtnEmpRegLogOut.setText("Log Out");
        jBtnEmpRegLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEmpRegLogOutActionPerformed(evt);
            }
        });

        jBtnEmpRegMain.setText("Main Menu");
        jBtnEmpRegMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEmpRegMainActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelEmpRegLayout = new javax.swing.GroupLayout(jPanelEmpReg);
        jPanelEmpReg.setLayout(jPanelEmpRegLayout);
        jPanelEmpRegLayout.setHorizontalGroup(
            jPanelEmpRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEmpRegLayout.createSequentialGroup()
                .addGroup(jPanelEmpRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelEmpRegLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addGroup(jPanelEmpRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jBtnDeleteCus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBtnAddCus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBtnEditCus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanelEmpRegLayout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(jLabel1)))
                .addContainerGap(109, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEmpRegLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jBtnEmpRegMain)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtnEmpRegLogOut)
                .addGap(24, 24, 24))
        );
        jPanelEmpRegLayout.setVerticalGroup(
            jPanelEmpRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEmpRegLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(45, 45, 45)
                .addComponent(jBtnAddCus)
                .addGap(18, 18, 18)
                .addComponent(jBtnEditCus)
                .addGap(18, 18, 18)
                .addComponent(jBtnDeleteCus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(jPanelEmpRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnEmpRegLogOut)
                    .addComponent(jBtnEmpRegMain))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelEmpReg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelEmpReg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnAddCusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAddCusActionPerformed
        AddCusView addCus=new AddCusView();
        this.dispose();
        addCus.setVisible(true);
    }//GEN-LAST:event_jBtnAddCusActionPerformed

    private void jBtnEditCusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEditCusActionPerformed
        SearchClientView editCus=new SearchClientView();
        this.dispose();
        editCus.setVisible(true);
    }//GEN-LAST:event_jBtnEditCusActionPerformed

    private void jBtnDeleteCusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDeleteCusActionPerformed
        DeleteCusView deleteCus=new DeleteCusView();
        this.dispose();
        deleteCus.setVisible(true);
    }//GEN-LAST:event_jBtnDeleteCusActionPerformed

    private void jBtnEmpRegMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEmpRegMainActionPerformed
        MainMenuView main=new MainMenuView();
        this.dispose();
        main.setVisible(true);
    }//GEN-LAST:event_jBtnEmpRegMainActionPerformed

    private void jBtnEmpRegLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEmpRegLogOutActionPerformed
        EmpLoginView login=new EmpLoginView();
        this.dispose();
        login.setVisible(true);
    }//GEN-LAST:event_jBtnEmpRegLogOutActionPerformed

    /**
     * @param args the command line arguments
     
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CusRegistrationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CusRegistrationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CusRegistrationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CusRegistrationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CusRegistrationView().setVisible(true);
            }
        });
    }
*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAddCus;
    private javax.swing.JButton jBtnDeleteCus;
    private javax.swing.JButton jBtnEditCus;
    private javax.swing.JButton jBtnEmpRegLogOut;
    private javax.swing.JButton jBtnEmpRegMain;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanelEmpReg;
    // End of variables declaration//GEN-END:variables
}
