/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package E_Bank_Client;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Raveen S Rathnayake
 */
public class CustomerPageView extends javax.swing.JFrame {

    /**
     * Creates new form AddEmpView
     */
    public CustomerPageView() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jBtnEditCus = new javax.swing.JButton();
        jLblHeading = new javax.swing.JLabel();
        jLbl1 = new javax.swing.JLabel();
        jLbl2 = new javax.swing.JLabel();
        jLbl3 = new javax.swing.JLabel();
        jLbl4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jBtnLogOut = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jBtnMain = new javax.swing.JButton();
        jBtnBack = new javax.swing.JButton();
        jLblMessage = new javax.swing.JLabel();
        jLbl5 = new javax.swing.JLabel();
        jLblName = new javax.swing.JLabel();
        jLblBday = new javax.swing.JLabel();
        jLblAddress = new javax.swing.JLabel();
        jLblMobile = new javax.swing.JLabel();
        jLblEmail = new javax.swing.JLabel();
        jLblAccType = new javax.swing.JLabel();
        jLblAccNum = new javax.swing.JLabel();
        jLblSortcode = new javax.swing.JLabel();
        jLblBalance = new javax.swing.JLabel();
        jLblCard = new javax.swing.JLabel();
        jBtnDeleteCus = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(400, 470));

        jBtnEditCus.setText("Edit Customer");
        jBtnEditCus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEditCusActionPerformed(evt);
            }
        });

        jLblHeading.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLblHeading.setText("Customer Details");

        jLbl1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLbl1.setText("Name");

        jLbl2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLbl2.setText("Birthdate");

        jLbl3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLbl3.setText("Address");

        jLbl4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLbl4.setText("Mobile");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Balance");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Account Type");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Account Number");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Sort Code");

        jBtnLogOut.setText("Log Out");
        jBtnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnLogOutActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Card");

        jBtnMain.setText("Main Menu");
        jBtnMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnMainActionPerformed(evt);
            }
        });

        jBtnBack.setText("Back");
        jBtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBackActionPerformed(evt);
            }
        });

        jLblMessage.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLbl5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLbl5.setText("Email");

        jLblName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLblBday.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLblAddress.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLblMobile.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLblEmail.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLblAccType.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLblAccNum.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLblSortcode.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLblBalance.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLblCard.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jBtnDeleteCus.setText("Delete Customer");
        jBtnDeleteCus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDeleteCusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(jLblHeading))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLbl4)
                                    .addComponent(jLbl3)
                                    .addComponent(jLbl2)
                                    .addComponent(jLbl1)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(44, 44, 44))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLbl5)
                                .addGap(122, 122, 122)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLblCard, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLblMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLblName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLblBday, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLblAddress, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLblMobile, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLblEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLblAccType, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLblAccNum, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLblSortcode, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLblBalance, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jBtnEditCus)
                        .addGap(45, 45, 45)
                        .addComponent(jBtnDeleteCus))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jBtnBack))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(146, 146, 146)
                                .addComponent(jBtnMain)))
                        .addGap(62, 62, 62)
                        .addComponent(jBtnLogOut)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLblHeading)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbl1)
                    .addComponent(jLblName))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbl2)
                    .addComponent(jLblBday))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbl3)
                    .addComponent(jLblAddress))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLbl4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLblMobile)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbl5)
                    .addComponent(jLblEmail))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLblAccType))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLblAccNum))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLblSortcode))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLblBalance))
                .addGap(18, 18, 18)
                .addComponent(jLblMessage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblCard))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnEditCus)
                    .addComponent(jBtnDeleteCus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnLogOut)
                    .addComponent(jBtnMain)
                    .addComponent(jBtnBack))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnEditCusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEditCusActionPerformed
        String email=jLblEmail.getText();
        int accNum=Integer.valueOf(jLblAccNum.getText());
            if(loadClient(accNum,email)==null){
                JOptionPane.showMessageDialog(this,"Error! No user found. Try again");
            }else{
                EditCusView cus=new EditCusView();
                this.dispose();
                    
                List<String> arrayList = loadClient(accNum,email);
                String[] array = new String[arrayList.size()];
                array = arrayList.toArray(array);
                cus.setFieldValues(array);
                    
                cus.setVisible(true);
                } 
    }//GEN-LAST:event_jBtnEditCusActionPerformed

    private void jBtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBackActionPerformed
        this.dispose();
        ViewCustomerView viewObj=new ViewCustomerView();
        viewObj.showList((ArrayList)displayClientList());
        viewObj.setVisible(true);
    }//GEN-LAST:event_jBtnBackActionPerformed

    private void jBtnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLogOutActionPerformed
        EmpLoginView login=new EmpLoginView();
        this.dispose();
        login.setVisible(true);
    }//GEN-LAST:event_jBtnLogOutActionPerformed

    private void jBtnMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnMainActionPerformed
        MainMenuView main=new MainMenuView();
        this.dispose();
        main.setVisible(true);
    }//GEN-LAST:event_jBtnMainActionPerformed

    private void jBtnDeleteCusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDeleteCusActionPerformed
        DeleteCusView deleteCus=new DeleteCusView();
        this.dispose();
        String email=jLblEmail.getText();
        String accNum=jLblAccNum.getText();
        deleteCus.setValues(accNum, email);
        deleteCus.setVisible(true);
    }//GEN-LAST:event_jBtnDeleteCusActionPerformed
   
    public void setFieldValues(String[] array){
        jLblName.setText(array[0]);
        jLblBday.setText(array[1]);
        jLblAddress.setText(array[2]);
        jLblMobile.setText(array[3]);
        jLblEmail.setText(array[4]);
        jLblAccNum.setText(array[5]);
        jLblSortcode.setText(array[7]);
        jLblBalance.setText(array[8]);
        jLblCard.setText(array[9]);
        jLblAccType.setText(array[6]);
    
    }
    /**
     * @param args the command line arguments
     
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddCusView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddCusView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddCusView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddCusView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddCusView().setVisible(true);
            }
        });
    } */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnBack;
    private javax.swing.JButton jBtnDeleteCus;
    private javax.swing.JButton jBtnEditCus;
    private javax.swing.JButton jBtnLogOut;
    private javax.swing.JButton jBtnMain;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLbl1;
    private javax.swing.JLabel jLbl2;
    private javax.swing.JLabel jLbl3;
    private javax.swing.JLabel jLbl4;
    private javax.swing.JLabel jLbl5;
    private javax.swing.JLabel jLblAccNum;
    private javax.swing.JLabel jLblAccType;
    private javax.swing.JLabel jLblAddress;
    private javax.swing.JLabel jLblBalance;
    private javax.swing.JLabel jLblBday;
    private javax.swing.JLabel jLblCard;
    private javax.swing.JLabel jLblEmail;
    private javax.swing.JLabel jLblHeading;
    private javax.swing.JLabel jLblMessage;
    private javax.swing.JLabel jLblMobile;
    private javax.swing.JLabel jLblName;
    private javax.swing.JLabel jLblSortcode;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    private static java.util.List<java.lang.String> loadClient(int arg0, java.lang.String arg1) {
        e_bank_ws.EBankClient_Service service = new e_bank_ws.EBankClient_Service();
        e_bank_ws.EBankClient port = service.getEBankClientPort();
        return port.loadClient(arg0, arg1);
    }

    private static java.util.List<java.lang.String> displayClientList() {
        e_bank_ws.EBankClient_Service service = new e_bank_ws.EBankClient_Service();
        e_bank_ws.EBankClient port = service.getEBankClientPort();
        return port.displayClientList();
    }

    
}
